import io

block = """
# ════════════════════════════════════════════════════════════════════════════
# PART 2 — remaining stale tokens in embedded source/tests + standalone docs
# ════════════════════════════════════════════════════════════════════════════

# offline_service.py: 59-country -> 200-country
repl("backend/services/offline_service.py",
'\"\"\"GET /offline-pack \u00b7 serves the bundled 59-country emergency number database.',
'\"\"\"GET /offline-pack \u00b7 serves the bundled 200-country emergency number database.',
label="offline_service.py docstring")
repl("backend/services/offline_service.py",
'@offline_router.get("/offline-pack", summary="Bundled 59-country emergency numbers")',
'@offline_router.get("/offline-pack", summary="Bundled 200-country emergency numbers")',
label="offline_service.py summary")

# rate_limiter.py: misleading default docstring
repl("backend/services/rate_limiter.py",
'    \"\"\"Token-bucket per client IP. Default: 30 requests/minute, burst of 10.\"\"\"',
'    \"\"\"Token-bucket per client IP. Deployed limits: 120/min (search), 80/min (triage).\"\"\"',
label="rate_limiter.py docstring")

# routeCache.js: stale 30/min comment
repl("frontend/src/utils/routeCache.js",
" *   the backend's per-IP rate limiter (30/min) or burn API quota.",
" *   the backend's per-IP rate limiter (120/min) or burn API quota.",
label="routeCache.js comment")

# README: fabricated Plus Code example -> real Chennai code
repl("README.md",
"**dispatcher-friendly Plus Code** like `7M5CC9R6+VV` \u2014 recognized by Indian 112 ERSS",
"**dispatcher-friendly Plus Code** like `7M5237MC+37` \u2014 recognized by Indian 112 ERSS",
label="README Plus Code example")

# README: /offline-pack API reference still said 59-country
repl("README.md", "Returns the bundled 59-country emergency number database.",
                   "Returns the bundled 200-country emergency number database.", label="README /offline-pack ref")

# medicalId.test.js: fabricated fixture -> the REAL code for the test's own coords
repl("frontend/src/utils/__tests__/medicalId.test.js",
"      plusCode: '7J5CC9R6+VV',", "      plusCode: '7M5237MC+37',", label="medicalId.test fixture input")
repl("frontend/src/utils/__tests__/medicalId.test.js",
"    expect(body).toMatch(/7J5CC9R6\\\\+VV/);", "    expect(body).toMatch(/7M5237MC\\\\+37/);", label="medicalId.test assertion")

# build_submission_tex.py: hardcoded crash prose now matches the new code
repl("scripts/build_submission_tex.py",
'        "On auto-detected crash (velocity collapse \u2265 25 km/h \u2192 \u2264 5 km/h in 2 s confirmed by \u2265 3.5 G accelerometer spike), a 10 s cancellation window lets the user abort false positives.",',
'        "On auto-detected crash (sustained \u2265 40 km/h collapsing to \u2264 5 km/h within ~2.5 s, optionally confirmed by a \u2265 3.5 G accelerometer spike), a cancellation window lets the user abort false positives.",',
label="build_submission_tex.py assumptions crash line")
repl("scripts/build_submission_tex.py",
\"\"\"  \\\\item \\\\textbf{Signal 1} --- GPS velocity collapse: $\\\\geq$25\\\\,km/h $\\\\to$
        $\\\\leq$5\\\\,km/h within 2\\\\,s.
  \\\\item \\\\textbf{Signal 2} --- Accelerometer spike: peak magnitude $\\\\geq$3.5\\\\,G.
  \\\\item \\\\textbf{Confirmation}: both signals must occur within a 4\\\\,s alignment window.\"\"\",
\"\"\"  \\\\item \\\\textbf{Signal 1 (primary)} --- GPS velocity collapse: sustained $\\\\geq$40\\\\,km/h $\\\\to$
        $\\\\leq$5\\\\,km/h within ~2.5\\\\,s. Tuned to reject ordinary braking and stop-and-go traffic.
  \\\\item \\\\textbf{Signal 2 (optional)} --- Accelerometer spike: peak magnitude $\\\\geq$3.5\\\\,G.
  \\\\item \\\\textbf{Confirmation}: the accelerometer spike, when motion permission is granted, must align within a 4\\\\,s window; a sustained-speed sudden stop alone still triggers.\"\"\",
label="build_submission_tex.py crash signals block")

# ── Standalone docs (NOT regenerated by the script — fix directly) ─────────
repl("docs/TECHNICAL.tex", "internationalization across 43 languages,", "internationalization across 48 languages,", label="TECHNICAL.tex scope")
repl("docs/TECHNICAL.tex", "|   |- i18next 26       (43 languages, RTL support)             |",
                           "|   |- i18next 26       (48 languages, RTL support)             |", label="TECHNICAL.tex diagram")
repl("docs/TECHNICAL.tex", "i18n & i18next 26.2.0 + react-i18next 17.0.8; 43 locales \\\\\\\\",
                           "i18n & i18next 26.2.0 + react-i18next 17.0.8; 48 locales \\\\\\\\", label="TECHNICAL.tex stack table")
repl("docs/TECHNICAL.tex",
"On first launch, the user sees a full-screen modal listing all 43 languages, grouped into ``India'' (22) and ``World'' (21) sections.",
"On first launch, the user sees a full-screen modal listing all 48 languages, grouped into ``India'' (22) and ``World'' (26) sections.",
label="TECHNICAL.tex language modal")
repl("docs/TECHNICAL.tex",
"A velocity collapse is registered when a sample at $\\\\ge$ 25 km/h is followed within 2 seconds by a sample at $\\\\le$ 5 km/h.",
"A velocity collapse is registered when sustained samples at $\\\\ge$ 40 km/h are followed within ~2.5 seconds by a sample at $\\\\le$ 5 km/h (tuned to reject ordinary braking and stop-and-go traffic).",
label="TECHNICAL.tex crash algo prose")
repl("docs/TECHNICAL.tex",
"Crash detection --- velocity collapse threshold & $\\\\ge$25 km/h $\\\\rightarrow$ $\\\\le$5 km/h within 2 s \\\\\\\\",
"Crash detection --- velocity collapse threshold & sustained $\\\\ge$40 km/h $\\\\rightarrow$ $\\\\le$5 km/h within ~2.5 s \\\\\\\\",
label="TECHNICAL.tex crash threshold table")

repl("docs/ARCHITECTURE.md", "\u2502  \u251c\u2500 i18next (43 languages)                                          \u2502",
                             "\u2502  \u251c\u2500 i18next (48 languages)                                          \u2502", label="ARCHITECTURE.md diagram")
repl("docs/ARCHITECTURE.md",
"- **43 languages:** all 22 Indian Schedule-VIII languages + English + 20 global (Spanish, French, Portuguese, German, Italian, Dutch, Polish, Russian, Ukrainian, Romanian, Greek, Turkish, Arabic, Persian, Hebrew, Swahili, Amharic, Indonesian, Malay, Thai, Vietnamese, Chinese, Japanese, Korean, Filipino)",
"- **48 languages:** all 22 Indian Schedule-VIII languages + English + 25 global (Spanish, French, Portuguese, German, Italian, Dutch, Polish, Russian, Ukrainian, Romanian, Greek, Turkish, Arabic, Persian, Hebrew, Swahili, Amharic, Indonesian, Malay, Thai, Vietnamese, Chinese, Japanese, Korean, Filipino). Hindi, Tamil, Bengali, Telugu and the major global languages are fully localised; Bodo, Kashmiri and Manipuri are partially localised.",
label="ARCHITECTURE.md language list")
repl("docs/ARCHITECTURE.md",
"10. **43-language i18n with RTL.** Cover all 22 Indian Schedule-VIII languages plus 20 global.",
"10. **48-language i18n with RTL.** Cover all 22 Indian Schedule-VIII languages plus 25 global + English.",
label="ARCHITECTURE.md summary")
repl("docs/ARCHITECTURE.md",
"1. **GPS velocity collapse:** \u226525 km/h followed by \u22645 km/h within 2-second window",
"1. **GPS velocity collapse:** sustained \u226540 km/h followed by \u22645 km/h within ~2.5 s (rejects ordinary braking)",
label="ARCHITECTURE.md crash threshold")

repl("docs/PRESENTATION.md", "Bundled 196-Country DB", "Bundled 200-Country DB", label="PRESENTATION.md DB label")

print("\\nPART 2 + DOCS DONE.")
"""

with io.open("fix_roadsos.py", "a", encoding="utf-8") as f:
    f.write(block)
